I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 49, in script
    $ renpy.pause(hard=True)
ScriptError: could not find label 'label2'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "D:\renpy-8.0.3-sdk\renpy-8.0.3-sdk\renpy\bootstrap.py", line 275, in bootstrap
    renpy.main.main()
  File "D:\renpy-8.0.3-sdk\renpy-8.0.3-sdk\renpy\main.py", line 670, in main
    run(restart)
  File "D:\renpy-8.0.3-sdk\renpy-8.0.3-sdk\renpy\main.py", line 144, in run
    renpy.execution.run_context(True)
  File "D:\renpy-8.0.3-sdk\renpy-8.0.3-sdk\renpy\execution.py", line 953, in run_context
    context.run()
  File "game/script.rpy", line 49, in script
    $ renpy.pause(hard=True)
  File "D:\renpy-8.0.3-sdk\renpy-8.0.3-sdk\renpy\script.py", line 1013, in lookup
    raise ScriptError("could not find label '%s'." % str(original))
ScriptError: could not find label 'label2'.

Windows-10-10.0.19045 AMD64
Ren'Py 8.1.1.23060707
MeMary 1.0
Tue Sep 19 09:02:10 2023
